
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author meher
 */
public class Event_Ammount extends javax.swing.JFrame {

    /**
     * Creates new form Event_Ammount
     */
    Connection con;

    public Event_Ammount() {
        initComponents();

        try {
            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=event_management;selectMethod=cursor", "sa", "123456");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error in connection", JOptionPane.INFORMATION_MESSAGE);
        }
        showAll();
        getsum();
    }

    Ammount_info jtRowData = new Ammount_info();

    //Ammount_info jtRowData = new Ammount_info();
    public void getsum() {
        double sum = 0;
        for (double i = 0; i < table11.getRowCount(); i++) {
            sum = (double) (sum + Double.parseDouble(table11.getValueAt((int) i, 10).toString()));
        }
        totalnum.setText(Double.toString((double) sum).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        table11 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totalnum = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Amount");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 33, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 89, 430, -1));

        table11.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        table11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "event_no", "staff_name", "client_name", "catering_price", "venue_price", "total"
            }
        ));
        table11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table11MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table11);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 198, 851, 180));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, -1, -1));

        totalnum.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jPanel1.add(totalnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 149, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, 30));

        jTextField1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 130, 186, 30));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Event ID :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 134, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/star1.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 80, 50));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/star1.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/i3.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1010, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void table11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table11MouseClicked
        // TODO add your handling code here:

        int index = table11.getSelectedRow();
        TableModel model = table11.getModel();

        String event_no = model.getValueAt(index, 0).toString();
        String staff_name = model.getValueAt(index, 1).toString();
        String client_name = model.getValueAt(index, 2).toString();
        String catering_price = model.getValueAt(index, 3).toString();
        String package_price = model.getValueAt(index, 4).toString();
        String photograhy_price = model.getValueAt(index, 5).toString();
        String transport_price = model.getValueAt(index, 6).toString();
        String venue_price = model.getValueAt(index, 7).toString();
        String date = model.getValueAt(index, 8).toString();
        String people = model.getValueAt(index, 9).toString();
        String total = model.getValueAt(index, 10).toString();

        jtRowData.setVisible(true);
        jtRowData.pack();
        jtRowData.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        jtRowData.jTextField1.setText(event_no);
        jtRowData.jTextField2.setText(staff_name);
        jtRowData.jTextField3.setText(client_name);
        jtRowData.jTextField4.setText(catering_price);
        jtRowData.jTextField5.setText(package_price);
        jtRowData.jTextField6.setText(photograhy_price);
        jtRowData.jTextField7.setText(transport_price);
        jtRowData.jTextField8.setText(venue_price);
        jtRowData.jTextField9.setText(date);
        jtRowData.jTextField10.setText(people);
        jtRowData.jTextField11.setText(total);
    }//GEN-LAST:event_table11MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            table11.print(JTable.PrintMode.NORMAL);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int a;
        a = JOptionPane.showConfirmDialog(null, "Do you really want to Close Application?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new home().setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:

        String tf = jTextField1.getText();

        try {
            String sql = "select event.eventid as 'event no', staff_details.name as 'staff_name', client_details.name as 'client_name', \n"
                    + "((catering.price)*(event.people)) as 'catering_price', EventPackage.price as 'Package_price', \n"
                    + "photography.price as 'Photography_price', transport.price as 'Transport_price', \n"
                    + "venue.price as 'venue_price', event.event_date as 'date', event.people as 'people',\n"
                    + "(catering.price + venue.price + EventPackage.price+ photography.price+ transport.price+ venue.price) as 'total'\n"
                    + "from event inner join staff_details \n"
                    + "on event.staff_id= staff_details.staff_id \n"
                    + "inner join client_details on event.client_id= client_details.client_id \n"
                    + "inner join catering on event.catering_id=catering.catering_id \n"
                    + "inner join EventPackage on event.PackageId=Eventpackage.PackageId \n"
                    + "inner join photography on event.PhotographyId=photography.PhotographyId \n"
                    + "inner join transport on event.transport_id=transport.transport_id \n"
                    + "inner join venue on event.VenueID = venue.VenueId WHERE eventID LIKE '%" + tf + "%'";
            java.sql.Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            table11.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Event_Ammount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Event_Ammount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Event_Ammount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Event_Ammount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Event_Ammount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable table11;
    private javax.swing.JTextField totalnum;
    // End of variables declaration//GEN-END:variables
private void showAll() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        try {
            String sql = "select event.eventid as 'event no', staff_details.name as 'staff_name', client_details.name as 'client_name', \n"
                    + "((catering.price)*(event.people)) as 'catering_price', EventPackage.price as 'Package_price', \n"
                    + "photography.price as 'Photography_price', transport.price as 'Transport_price', \n"
                    + "venue.price as 'venue_price', event.event_date as 'date', event.people as 'people',\n"
                    + "(catering.price + venue.price + EventPackage.price+ photography.price+ transport.price+ venue.price) as 'total'\n"
                    + "from event inner join staff_details \n"
                    + "on event.staff_id= staff_details.staff_id \n"
                    + "inner join client_details on event.client_id= client_details.client_id \n"
                    + "inner join catering on event.catering_id=catering.catering_id \n"
                    + "inner join EventPackage on event.PackageId=Eventpackage.PackageId \n"
                    + "inner join photography on event.PhotographyId=photography.PhotographyId \n"
                    + "inner join transport on event.transport_id=transport.transport_id \n"
                    + "inner join venue on event.VenueID = venue.VenueId;";
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            table11.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);

        }

    }

}
